include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_declarations
    - cancel_subscriptions
    - close_sinks
    - always_declare_return_types
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_single_quotes
    - sort_child_properties_last
    - avoid_print
